spring:
  datasource:
    username: seven
    password: 12345678
    url: jdbc:mariadb://159.75.90.116:3306/vocation
    driver-class-name: org.mariadb.jdbc.Driver

  security:
    user:
      name: admin
      password: admin


